name: 'MLL With Integration Tests'
on: 'workflow_dispatch'
jobs:
  mll-with-tests:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2    
    - name: 'Apply Workflow Patches'
      run: |
        cd .github
        bash ./github-ci.sh  
    - name: 'Step 00 - Clean'
      run: |
        cd ./src
        bash ./00_clean.sh
    - name: 'Step 01 - Get Kernel'
      run: |
        cd ./src
        bash ./01_get_kernel.sh
    - name: 'Step 02 - Build Kernel'
      run: |
        cd ./src
        bash ./02_build_kernel.sh
    - name: 'Step 03 - Get GNU C Library'
      run: |
        cd ./src
        bash ./03_get_glibc.sh
    - name: 'Step 04 - Build GNU C Library'
      run: |
        cd ./src
        bash ./04_build_glibc.sh
    - name: 'Step 05 - Prepare Sysroot'
      run: |
        cd ./src
        bash ./05_prepare_sysroot.sh
    - name: 'Step 06 - Get Busybox'
      run: |
        cd ./src
        bash ./06_get_busybox.sh
    - name: 'Step 07 - Build Busybox'
      run: |
        cd ./src
        bash ./07_build_busybox.sh
    - name: 'Step 08 - Prepare Overlay Bundles'
      run: |
        cd ./src
        bash ./08_prepare_bundles.sh
    - name: 'Step 09 - Generate Root Filesystem'
      run: |
        cd ./src
        bash ./09_generate_rootfs.sh
    - name: 'Step 10 - Pack Root Filesystem'
      run: |
        cd ./src
        bash ./10_pack_rootfs.sh
    - name: 'Step 11 - Generate Overlay Area'
      run: |
        cd ./src
        bash ./11_generate_overlay.sh
    - name: 'Step 12 - Get Syslinux'
      run: |
        cd ./src
        bash ./12_get_syslinux.sh
    - name: 'Step 12 - Get Systemd-boot'
      run: |
        cd ./src
        bash ./12_get_systemd-boot.sh
    - name: 'Step 13 - Prepare ISO Image'
      run: |
        cd ./src
        bash ./13_prepare_iso.sh
    - name: 'Step 14 - Generate ISO Image'
      run: |
        cd ./src
        bash ./14_generate_iso.sh
    - name: 'Step 15 - Generate Docker Image'
      run: |
        cd ./src
        bash ./15_generate_image.sh
    - name: 'Step 16 - Final Cleanup'
      run: |
        cd ./src
        bash ./16_cleanup.sh
    - name: 'Test Docker'
      run: |
        cd .github
        bash ./test_docker.sh
    - name: 'Test QEMU'
      run: |
        cd .github
        bash ./test_qemu.sh
